server:
  port: 8761
spring:
  application:
    name: eureka-server01
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #是否将自己注册
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/