server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: server01
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #register-with-eureka: false #是否将自己注册,默认true
    #fetch-registry: false #是否从注册中心获取服务注册信息，默认true
    service-url:
      defaultZone: http://localhost:8762/eureka/