server:
  port: 8762
spring:
  application:
    name: eureka-server02
eureka:
  instance:
    hostname: localhost
  client:
    #register-with-eureka: false #是否将自己注册,默认true
    #fetch-registry: false #是否从注册中心获取服务注册信息，默认true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/