server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: server02
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 10 #获取服务间隔时间
  client:
    #register-with-eureka: false #是否将自己注册,默认true
    #fetch-registry: false #是否从注册中心获取服务注册信息，默认true
    service-url:
      defaultZone: http://localhost:8761/eureka/